# Generated by Django 6.0.2 on 2026-03-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_lifecycle_rework'),
        ('project_admin', '0004_productapprovalrequest_sellerapprovalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapprovalrequest',
            name='original_product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_approval_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='productapprovalrequest',
            name='request_type',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit')], default='create', max_length=10),
        ),
    ]
