# Generated by Django 6.0.2 on 2026-04-17 01:32

import django.db.models.deletion
import sellers.models
import sellers.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sellers.models.upload_icon_to, validators=[sellers.validators.validate_image_file])),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Blouse', 'Blouse'), ('Sweater', 'Sweater'), ('Hoodie', 'Hoodie'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Swimwear', 'Swimwear'), ('Sleepwear', 'Sleepwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_products', to='products.product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='buyers.orderitem')),
            ],
        ),
    ]
