# Generated by Django 6.0.2 on 2026-03-28 07:58

import products.models
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_icon_to, validators=[products.validators.validate_image_file]),
        ),
    ]
