# Generated by Django 6.0.2 on 2026-03-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_delete_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
