# Generated by Django 6.0.2 on 2026-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='buyer_name',
        ),
    ]
