# Generated by Django 6.0.2 on 2026-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_discount_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookurl',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhookurl',
            name='webhook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
