# Generated by Django 6.0.2 on 2026-03-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='despcription',
            new_name='description',
        ),
    ]
