# Generated by Django 6.0.2 on 2026-03-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_rename_despcription_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
