# Generated by Django 6.0.2 on 2026-03-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('buyers', '0004_initial'),
		('products', '0004_product_lifecycle_rework'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='BuyerShippingAddress',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('label', models.CharField(max_length=100)),
				('recipient_name', models.CharField(max_length=150)),
				('address_line_1', models.CharField(max_length=200)),
				('address_line_2', models.CharField(blank=True, max_length=200)),
				('city', models.CharField(max_length=100)),
				('state', models.CharField(max_length=100)),
				('postal_code', models.CharField(max_length=20)),
				('country', models.CharField(max_length=100)),
				('phone_number', models.CharField(blank=True, max_length=30)),
				('is_default', models.BooleanField(default=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shipping_addresses', to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.CreateModel(
			name='PaymentMethod',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('label', models.CharField(max_length=100)),
				('cardholder_name', models.CharField(max_length=150)),
				('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'Amex'), ('discover', 'Discover'), ('other', 'Other')], max_length=20)),
				('last_four', models.CharField(max_length=4)),
				('expiry_month', models.PositiveSmallIntegerField()),
				('expiry_year', models.PositiveSmallIntegerField()),
				('provider_reference', models.CharField(blank=True, max_length=100)),
				('is_default', models.BooleanField(default=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.CreateModel(
			name='SellerShippingAddress',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('label', models.CharField(max_length=100)),
				('recipient_name', models.CharField(max_length=150)),
				('address_line_1', models.CharField(max_length=200)),
				('address_line_2', models.CharField(blank=True, max_length=200)),
				('city', models.CharField(max_length=100)),
				('state', models.CharField(max_length=100)),
				('postal_code', models.CharField(max_length=20)),
				('country', models.CharField(max_length=100)),
				('phone_number', models.CharField(blank=True, max_length=30)),
				('is_default', models.BooleanField(default=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_shipping_addresses', to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.CreateModel(
			name='Order',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('order_number', models.CharField(max_length=30, unique=True)),
				('status', models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='placed', max_length=20)),
				('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
				('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
				('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
				('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
				('buyer_shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.buyershippingaddress')),
				('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.paymentmethod')),
				('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL)),
				('seller_shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.sellershippingaddress')),
			],
		),
		migrations.CreateModel(
			name='OrderItem',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('product_name', models.CharField(max_length=200)),
				('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
				('quantity', models.PositiveIntegerField()),
				('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
				('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyers.order')),
				('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
			],
		),
	]