# Generated by Django 6.0.2 on 2026-03-24 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_order_seller_data_to_items(apps, schema_editor):
	OrderItem = apps.get_model('buyers', 'OrderItem')

	for order_item in OrderItem.objects.select_related('order').all():
		order_item.seller_id = order_item.order.seller_id
		order_item.seller_shipping_address_id = order_item.order.seller_shipping_address_id
		order_item.save(update_fields=['seller', 'seller_shipping_address'])


class Migration(migrations.Migration):

	dependencies = [
		('buyers', '0005_checkout_models'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='orderitem',
			name='seller',
			field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='orderitem',
			name='seller_shipping_address',
			field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='buyers.sellershippingaddress'),
		),
		migrations.RunPython(copy_order_seller_data_to_items, migrations.RunPython.noop),
		migrations.AlterField(
			model_name='orderitem',
			name='seller',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(
			model_name='orderitem',
			name='seller_shipping_address',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='buyers.sellershippingaddress'),
		),
		migrations.RemoveField(
			model_name='order',
			name='seller',
		),
		migrations.RemoveField(
			model_name='order',
			name='seller_shipping_address',
		),
	]