# Generated by Django 6.0.2 on 2026-03-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('buyers', '0006_order_item_seller_shipping'),
	]

	operations = [
		migrations.AddField(
			model_name='paymentmethod',
			name='full_card_number',
			field=models.CharField(blank=True, default='', max_length=19),
		),
	]