# Generated by Django 6.0.2 on 2026-03-24 01:30

from django.db import migrations, models


def copy_order_status_to_order_items(apps, schema_editor):
	OrderItem = apps.get_model('buyers', 'OrderItem')

	for order_item in OrderItem.objects.select_related('order').all():
		order_item.item_status = order_item.order.status
		order_item.save(update_fields=['item_status'])


class Migration(migrations.Migration):

	dependencies = [
		('buyers', '0007_paymentmethod_full_card_number'),
	]

	operations = [
		migrations.AddField(
			model_name='orderitem',
			name='item_status',
			field=models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='placed', max_length=20),
		),
		migrations.RunPython(copy_order_status_to_order_items, migrations.RunPython.noop),
	]