# Generated by Django 6.0.2 on 2026-03-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0008_orderitem_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('returned', 'Returned')], default='placed', max_length=20),
        ),
    ]