# Generated by Django 6.0.2 on 2026-04-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyers", "0002_initial"),
        ("buyers", "0009_alter_orderitem_item_status"),
    ]

    operations = []
